# Generated by Django 2.2.4 on 2020-04-11 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('seasonCard', models.CharField(max_length=20)),
                ('symbolCard', models.CharField(max_length=20)),
                ('travelCard', models.CharField(max_length=20)),
                ('explain', models.TextField()),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
