# Generated by Django 2.2.4 on 2020-05-25 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('algorithm', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('answer', models.TextField()),
                ('note', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
